# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
#cache:
 # paths:
 # - node_modules/

stages:
  - test

test:
  stage: test
  only:
    - branches
  script:
    - git submodule sync
    - git submodule update --init --recursive --force
    - cd src
    - npm install
    - npm test
